name: tufan-v7-server

services:
  - name: tufan-web
    git:
      repo: https://github.com/rohit-091/Page___s3rv3r-t3st
      branch: main
    build:
      commands:
        - pip install -r requirements.txt
    run: gunicorn main:app --bind 0.0.0.0:$PORT
    ports:
      - port: 8000
        protocol: http
    regions:
      - fra
